name: fzwm_wxbc
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, buid-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.7.7+77

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  fzwm_wxbc_public:
    path: plugins/fzwm_wxbc_public
  intl: ^0.17.0
  crypto: any
  sprintf: ^6.0.0
  bluetooth_thermal_printer: ^0.0.6
  esc_pos_utils: any
  date_format: ^1.0.9
  gbk2utf8: ^1.0.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  # 瀑布流插件
  waterfall_flow: any
  # 屏幕适配插件
  flutter_screenutil: ^0.4.6
  # 第三方 icon 图标插件
  font_awesome_flutter: ^8.12.0
  # pda扫描
  pda_scanner: ^0.2.9
  # 二维码扫描
  qrscan: ^0.2.22
  # loading
  flutter_easyloading: ^1.3.0
  # 选择器
  flutter_pickers: ^1.0.2
  english_words: ^3.1.5
  # (缓存数据)
  shared_preferences: ^0.5.12+4
  # （网络请求）
  dio: ^3.0.10
  cookie_jar: ^1.0.1
  dio_cookie_manager: ^1.0.0
  # （吐司文字类比 Android里面的toast）
  toast: ^0.1.5
  fluttertoast: ^3.1.3
  json_annotation: any
  # 网络检测
  connectivity: ^2.0.2
  # pdf
  flutter_full_pdf_viewer: ^1.0.6
  path_provider: ^1.6.28
  flutter_webview_plugin: ^0.2.1+2
  package_info: ^0.4.3+4
  permission_handler: 5.0.0+hotfix.4
  open_file: 3.0.1
  flutter_downloader: 1.5.0
  progress_dialog: 1.2.0
  url_launcher: any
  # 本地数据库
  sqflite: ^2.0.2
  decimal: ^0.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
